FROM python:3.9.12-slim-buster

WORKDIR /Users/sarvinbaghi/Desktop/Network/Chat-Box/client

COPY . /Users/sarvinbaghi/Desktop/Network/Chat-Box/client

RUN pip install -r requirements.txt

ENTRYPOINT ["python", "client.py"]