FROM python:3.9.12-slim-buster

WORKDIR /Users/sarvinbaghi/Desktop/Network/Chat-Box/server

COPY . /Users/sarvinbaghi/Desktop/Network/Chat-Box/server

RUN pip install -r requirements.txt

ENTRYPOINT ["python", "server.py"]

